### ISSUE TITLE
Move Flinders attribution to 'footer'

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#1]
The Flinders attribution should be moved to a new `<div>` that does the following:

* where possible always displayed on one line
* display in much smaller font size
* fixed at the bottom of the page as a footer.
  * it can either be fixed at the bottom ie: always be present regardless of what is on the screen; or
  * it can be diplayed either at the end of a page (ie: scroll down to see it) or at the bottom where a page does not occupy a full screen.

Ask @mferrare if this isn't clear!

**Comment by mferrare** [comment]
@Sirage-t you think you could look after this one?  You're the CSS expert :-)

We can then re-use this for our other projects

**Comment by Sirage-t** [comment]
@mferrare 
Sure!

I'll pull the latest code from the `issue#2` branch and go from there?

**Comment by mferrare** [comment]
@Sirage-t need some additional changes:
1. Background should be same background as main screen (so, white in this case)
2. Text should centre-align with logo.  Seems to be bottom-aligned at the moment
3. I think also it could be placed closer to the bottom of the screen.  Interested in your thoughts though.

**Comment by Sirage-t** [comment]
@mferrare 
1. Easy 
2. I will try and find a solution. Had to do it this way because the top of the text was overflowing and being truncated on smaller screens.
3. this relates to point 2, in that the height is fixed, and I needed to accommodate for the text wrapping. I might use media query to adjust height based on screen size or use a responsive unit like `vh` or `vw` instead of `px`.

**Comment by Sirage-t** [comment]
@mferrare see PR Digital-Law-Lab/docassemble-LLAW33012020S2P06#17. I decided not to use a dynamic height, but a fixed one of 120px. This adds more whitespace between the main question section and the footer. I don't think this is necessarily a negative thing, so a fixed height should work for now. If you don't like the additional space I can try and experiment with other solutions that will adapt the height based on the width of the viewport.

**Comment by mferrare** [comment]
@Sirage-t I never accepted PR#17 and now this has been transferred to the new repo. Can you close the old PR and raise a new PR against `next` in this repo?
