### ISSUE TITLE
Quick Exit Button

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#10]

**Comment by mferrare** [comment]
Go here for quick exit button: https://github.com/LLAW3301/docassemble-LLAW33012020S1P02

**Comment by bahlahkay** [comment]
Note that quick exit button in navbar not likely to be a viable solution as will disappear on small devices e.g. mobiles) due to screen resizing. 

Explore "top" and "bottom" sections of interview blocks as alternatives and might need review in the irefer app

**Comment by mferrare** [comment]
Quick exit button needs to be added to first screen and last screen.

**Comment by mferrare** [comment]
Refer to #20 which deals with this also.
