### ISSUE TITLE
Welcome Screen Wording Changes:

### ISSUE THREAD

**Issue by bahlahkay** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#11]
* Replace title of the page with "How to get help"
* Replace "I do not agree" with "No Thanks"

**Comment by mferrare** [comment]
From P06 requirements:

Opening screen too ‘wordy’.  

- [x] Replace title of the page with ‘How to get help’
- [x] Replace ‘I do not agree’ with ‘No thanks’
- [x] Make the CLCSA logo smaller  
- [x] Privacy disclaimer smaller – maybe we can put it in small print under the buttons?
- [ ] Generally remove words and make language simpler

**Comment by mferrare** [comment]
Language is simpler and could go to Ippei (or peer review) for further work.  That covers numbers 1, 2 and 4.

Disclaimer and privacy replaced with 'Terms' which incorporate both.

Digital-Law-Lab/docassemble-clcsa-01-service-directory#7 might apply to the entire app.  Need to check with Ippei.

1. ~Replace title of the page with ‘How to get help’~
1. ~Replace ‘I do not agree’ with ‘No thanks’~
1. Make the CLCSA logo smaller  
1. ~Privacy disclaimer smaller – maybe we can put it in small print under the buttons?~
1. Generally remove words and make language simpler

**Comment by Sirage-t** [comment]
@mferrare 
The logo is indeed humongous. How much smaller should it be?

**Comment by mferrare** [comment]
If you have a look at https://clcsa.org.au you'll see there logo is huge there too

[Relevant DA Doco](https://docassemble.org/docs/initial.html#metadata) says default logo height is 20 pixels but can be adjusted but needs to be accompanied with CSS adjustments.

Not sure if 20px is too small but that logo looks way out of place that size.  Try 20px or 50px or 100px and see?  Also, the quality of the png is not very good.  CLCSA's logo on their website is much better.

**Comment by Sirage-t** [comment]
@mferrare  PR Digital-Law-Lab/docassemble-LLAW33012020S2P06#16 resized logo to 60px

**Comment by mferrare** [comment]
OK, so now we are at:

1. ~Replace title of the page with ‘How to get help’~
1. ~Replace ‘I do not agree’ with ‘No thanks’~
1. ~Make the CLCSA logo smaller~
1. ~Privacy disclaimer smaller – maybe we can put it in small print under the buttons?~
1. Generally remove words and make language simpler 

Just No 5 to go.

**Comment by mferrare** [comment]
I'm noting #17 but will close this #11 as wording is suitable for next release.
