### ISSUE TITLE
Final screen displays nothing when there are no applicable services

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#14]
### Describe the issue

Two issues:

1. If no services are returned for a set of parameters, then the final screen should say words to the effect that no services could be found and redirect user somewhere.
2.  From memory, the app should never return no services.  Need to test situations when there are no services returned.  My understanding is that a set of generic services should always be returned.

### What did you expect to happen?

1. Explanatory text displayed when no services returned
2. Confirm that some generic services should always be returned

### Have you checked that the issue has not already been raised?

- [X] I did not find any similar issues

**Comment by Sirage-t** [comment]
This is a critical "internal" issue. I hope we won't need to rewrite any internal logic but I'll have a look and report back once I've located the delinquent piece of code.

**Comment by mferrare** [comment]
Example of inputs that lead to no results.

![image](https://user-images.githubusercontent.com/582798/220813140-de397246-47ff-4c46-b57f-8f04b409d11d.png)
