### ISSUE TITLE
Remove words from CLCSA logo in navbar

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#15]
### Problem

Logo is now so small words can't be read.  Only display the logo

### Have you checked that the issue has not already been raised?

- [X] I did not find any similar issues or feature requests

**Comment by Sirage-t** [comment]
@mferrare  This requires modification of the logo image itself. I can do it but would CLCSA approve this?

**Comment by mferrare** [comment]
I've done it.  I think this is one of these things where it's better to ask for forgiveness :-)
