### ISSUE TITLE
[Feature]: convert welcome screen to use accordion menu

### ISSUE THREAD

**Issue by Sirage-t** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#17]
### Problem

This relates to #11, which states that the welcome screen is too cluttered and wordy.

The existing solution was to make the font size smaller and other style changes. However, there are three issues with this, two of which are related to accessibility: 1) not all people have great eyesight; 2) it does not work well with screen readers; and 3) the welcome screen is still "cluttered". 

The second issue is quite complex and requires multiple issues to be raised separately (i.e. the screen reader does not read any of the content on the screen when navigating with `tab` key. if you use the cursor to click it reads it but that is not how it is supposed to work)

### Proposed Solution

The solution I propose is to use an accordion based layout, effectively hiding the privacy statement and disclaimer away. 

In terms of the issues above:
1. font size doesn't need to be smaller
2. A screen reader would identify this as a box that can be expanded and the user can make the decision whether to read its content or not.
3. the text is visually hidden until expanded

This will partially fix the screen reader issue.

### Have you checked that the issue has not already been raised?

- [X] I did not find any similar issues or feature requests

**Comment by Sirage-t** [comment]
@mferrare ^

**Comment by mferrare** [comment]
Noted. Thanks.

**Comment by mferrare** [comment]
No longer relevant due to change in scope by client
