### ISSUE TITLE
Reform list of services

### ISSUE THREAD

**Issue by Sirage-t** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#21]
This is a sibling of #6.

As part of the internal changes, I am separating the list of services from the filtering logic. 

However, I noticed that the services do not adhere to a uniform schema. 

#### Address

For instance, most services have a single address, but some include two or more. This should be prohibited. The reasoning is quite straightforward: we should only show a service that matches the selected location. The current approach disregards the provided location data and instead shows a list of addresses some of which will be irrelevant to the user. Having multiple addresses prevents us from filtering the list based on location, making the location filter useless at times - sometimes it works and others it doesn't. This is unacceptable. All filters should behave the same and have the same effect. Consistency is important.

My suggestion is that each service should indicate a specific branch rather than the overarching organisation (we can already see this pattern for some service, we just need to uniform).  If anyone has better suggestions please don't abstain. 

#### Phone Number

This field is in true chaos. At times it is a number and at times it contains text like "(08) 8232 2282 (Catherine House) outreach times by appointment". Even worse, it sometimes contains more than one number - occasionally one for each address! (This is should be resolved by implementing the preceding). There several issues here. The most important is that we can't have a clickable phone number (unless we extract the number for the text - which I don't recommend). Other issues include inconsistency and undermined maintainability (the code will be unnecessarily more complex in order to account to all cases). 

The easiest solution is to be strict. Phone number can only contain a phone number and only a single one.  This will be the primary number and is actionable (the user can click it to call)  To support more than one, we could have a secondary number, tertiary, and so forth as additional metadata (I will call them Condiments - you could suggest a better name).  

#### Condiments 

This constitutes any additional elements that will be displayed under each service and does not include compulsory data (name, url, phone number, address, and logo). 
Condiments are optional and variable (they don't have to be included for all service, nor do they have to consistent).

However, they follow a uniform signature:
```json
{
"label": "i.e. Freecall",
"icon": "svg/link or Font Awesome icon",
"value": "i.e. 1800 111 052",
"help": "more info"
}
```
`Label`, `Icon`, and `Help` are optional. The content of `Icon` should either be a link for an svg, a name of a decoration, or a name of a Font Awesome icon - see [Inline Icons](https://docassemble.org/docs/markup.html#emoji) for more detail.
`Value` contains any text you want. `Help` contains addition information that would be shown when the user hover over an ❕ icon next to the `Label`.

**Finally**
The list of service would be extracted from a spreadsheet for ease of modification and review by client.

**Comment by mferrare** [comment]
I agree the data is a bit of a mess.  I think your proposal to deal with it is good.  Go ahead and let me know if you need help.
