### ISSUE TITLE
Migrate filter conditions out of `legacy - CLCSA_List_of_Services.yml` to `Config_Store.yml`

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#23]

**Comment by mferrare** [comment]
This hasn't done

**Comment by mferrare** [comment]
@bahlahkay try to do this over the weekend

**Comment by bahlahkay** [comment]
Haven't made any progress on this - we can discuss at the meeting but is the legacy yaml file in sirage's next branch or master - the repo was indicating that last commit was last month?

**Comment by mferrare** [comment]
@Sirage-t suggests create the entries in `directoryManagement.py` because, as it's a Python file, we'll get syntax highlighting which will help to ensure we don't get syntax errors.  Once created in `directoryManagement.py`, then migrate to `Config_Store.yml`.

**Comment by mferrare** [comment]
I've done this.  Results are in `next_sirage`
