### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#26]
If I input the following:
- Domestic Violence
- South
- Not Aboriginal
- Female

I would expect to see a list with INDIO and Women's legal centre at the top.  However, as 2nd and third results I get JusticeNet and Refugee Advocacy, neither of which deal with DV.  Women's Legal Service doesn't appear.

![image](https://user-images.githubusercontent.com/582798/230831973-b041d082-f651-43d8-8305-4448c6885bc6.png)

_Originally posted by @mferrare in https://github.com/Digital-Law-Lab/docassemble-clcsa-01-service-directory/issues/24#issuecomment-1501410655_

**Comment by mferrare** [comment]
Not sure if it's related but I notice that the original data block had entries for gender and indigenous for all entries but it seems that `_contractsList` does not.

**Comment by Sirage-t** [comment]
PR #24 fixed the sorting at line 565 of `directoryManagement.py` and activated the hurdle requirement for the `legalIssue` question (which ensures that only those services that deal with the selected legal area are displayed - previously it treated non-matches as `close match` like 'Refugee Advocacy' in this case). I also fixed the ID for `Women's Legal Service` which was causing the issue.
