### ISSUE TITLE
Male, female, other icons on gender screen are different sizes

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#28]
### Describe the issue

Male is fatter than female and other is skinnier still.  They should all look the same.

![image](https://user-images.githubusercontent.com/582798/235281844-d6008a61-3f6c-43cb-b327-70883ddce3b3.png)

### What did you expect to happen?

They should all look the same.

### Have you checked that the issue has not already been raised?

- [X] I did not find any similar issues

**Comment by Sirage-t** [comment]
I have created proper svg icons to replace existing ones. (I also fixed some padding and alignment issues).

![image](https://user-images.githubusercontent.com/47163720/235336600-b907c994-3bfd-4216-a52c-31a563ed22d6.png)
