### ISSUE TITLE
CSS Changes:

### ISSUE THREAD

**Issue by bahlahkay** [Digital-Law-Lab/docassemble-CLCSA01ServiceDirectory#9]
* Make the CLCSA logo smaller - on welcome page/opening screen.
* Add text formatting to make the privacy disclaimer smaller (change to small print under buttons) on welcome page.

**Comment by Sirage-t** [comment]
@mferrare I think this issue is already covered in Digital-Law-Lab/docassemble-clcsa-01-service-directory#11. Should we close it?

**Comment by mferrare** [comment]
Agreed.  Closed.
